### ISSUE TITLE
Radix and Puck styles clashing

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#106]
Various issues occur when using Radix with Puck resulting in illegible text.

See below screenshot from FF on MacOS, running dark mode and Radix using system theme.

![image](https://github.com/measuredco/puck/assets/985961/824e916e-c39c-4661-a2a3-60b816d44e4d)

Reported by @gothfemme in Discord.

**Comment by chrisvxd** [comment]
#105 should fix some of the style pollution in the heading analyzer plugin

**Comment by gothfemme** [comment]
@chrisvxd what are your thoughts on having either Puck or the preview root render in a portal? Thinking it could work as a longer-term solution for sandboxing the styles and keeping the preview root closer to the document root for inheritance. Would likely require some layout finessing but nothing too drastic I imagine...

**Comment by chrisvxd** [comment]
Hm use of a Portal is interesting, but iframes I'd like to avoid for now.

Curious if that would help with the radix issue, or if it's actually global styles polluting the Puck styles.

**Comment by gothfemme** [comment]
Portals wouldn't create an iframe! Just would render the preview as a direct child of the document body, outside of Puck's DOM Tree. It does seem this issue happens even in setups where the `html` style is just `background: black; color: white;`, regardless of Radix. Another issue I ran into that led me to thinking about this is Puck's preview frame background getting inherited by the site preview

**Comment by chrisvxd** [comment]
Sure, I just meant I didn't want to explore iframes as well, or that's something you were considering for style isolation.
