### ISSUE TITLE
Include richer hooks for formatting External Data

### ISSUE THREAD

**Issue by FreddieRidell** [measuredco/puck#147]
related to: https://github.com/measuredco/puck/pull/146

Currently puck will naively print all fields from each External Data instace in the ExternalInput modal. This could be improved by extending the `Adaptor` type to include a function to format the data for display:

## Option 1
Return an object of the values we want, stringified, let puck handle the rendering:

```tsx
function selectVisibleFields(item: {name: string, description: string, link: { url: string, label: string }) {
  return { 
    name: item.name,
    description: item.description
    linkUrl: link.url,
    //link label excluded
  }
}
```

## Option 2
Return a component that is rendered as a table row:

```tsx
function renderItemRow(item: {name: string, description: string, link: { url: string, label: string }) {
  return <PuckRow>
    <PuckCell>{name}</PuckCell>
    <PuckCell>{description}</PuckCell>
    <PuckCell><PuckLinkPreview href={link.url}>{link.label}</PuckLinkPreview></PuckCell>
  </PuckRow>
}

**Comment by chrisvxd** [comment]
Rewording this to reflect current state of external fields.

**Comment by chrisvxd** [comment]
Scrap that - closing it as the specific ask here his done. Will open an additional ticket for further work.
