### ISSUE TITLE
toggle LeftSideBar visibility is impossible with renderHeader 

### ISSUE THREAD

**Issue by ahmedrowaihi** [measuredco/puck#152]
# PR: https://github.com/measuredco/puck/pull/151
## Issue: 
when you use ```renderHeader``` in ```puck component``` the side bar toggle is vanished as well, so I created this PR to fix it

**Comment by chrisvxd** [comment]
@ahmedrowaihi do you still need this? I'm not sure you can _read_ the appState in the header yet.
