### ISSUE TITLE
Custom Plugin renderFields to check for selected component

### ISSUE THREAD

**Issue by sagarchoudhary96** [measuredco/puck#167]
I want to show some Custom Fields/Button for each Component and using custom Plugin `renderFields` method for the same. it has children and data props but currently there is not way to know which component is selected, which is need to read the correct content from the data prop and do further actions accordingly. is there a way to do it currently or if it can be a quick implementation, would be great to have it.

**Comment by sagarchoudhary96** [comment]
cc: @chrisvxd

**Comment by chrisvxd** [comment]
@sagarchoudhary96 I believe this should be resolved by #163, which was just merged.

You can now access `state` in your renderFields function. Specifically, you can check `state.ui.itemSelector` to see which item is currently selected, but you'll have to look it up in the data (now exposed under `state.data`).

Let me know if that helps

**Comment by sagarchoudhary96** [comment]
When these changes will be released.

**Comment by chrisvxd** [comment]
Ah yea, should be available in canary: `0.10.0-canary.e308381`

**Comment by sagarchoudhary96** [comment]
That works and is  how i was as well expecting it to be there, thanks to the team for amazing work :)

**Comment by chrisvxd** [comment]
Thank you @sagarchoudhary96! I'll close this issue.
