### ISSUE TITLE
Array type props throwing error if undefined

### ISSUE THREAD

**Issue by sagarchoudhary96** [measuredco/puck#179]
@chrisvxd  In the recent V0.10.0, i'm seeing an error which is being thrown if there is a props defined of type Array but if  that value is not present in props i.e it is undefined then it's throwing error when selecting that component. i belive this is what causing it -> https://github.com/measuredco/puck/blob/922a83913ae2cb402d0e8fa075cbcc0c906b61cc/packages/core/components/InputOrGroup/fields/ArrayField/index.tsx#L33C12-L33C29

<img width="269" alt="Screenshot 2023-10-20 at 4 43 23 AM" src="https://github.com/measuredco/puck/assets/16102594/fb919a68-54f5-43f7-b219-66ceb0c08c4d">

If we can add a check here for value to be defined or use empty array it should work. 

```
Array.from(value || [])
```

**Comment by chrisvxd** [comment]
@sagarchoudhary96 please confirm if this is resolved in `0.10.1-canary.47ab3c9`

**Comment by sagarchoudhary96** [comment]
@chrisvxd  tested it out and it fixes the issue.

**Comment by chrisvxd** [comment]
Awesome, closing now. Thanks @sagarchoudhary96!

**Comment by sagarchoudhary96** [comment]
@chrisvxd i missed one check in previous PR, ihave raised another PR for same.
