### ISSUE TITLE
Add more behaviour to plugins

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#18]
* `setData` prop to allow plugins to override the data
* A mechanism to block page publishing (for example, if the heading outline is invalid in `plugin-heading-analyzer`)

**Comment by johannbuscail** [comment]
Hey @chrisvxd, any update on this ? This is a feature that's really needed, especially the `setData` method. 
I'm using Puck with AI, and it would be a game changer to be able to modify the editor data even after init.

Thanks !

**Comment by johannbuscail** [comment]
I think in general, the best way to access a `setData` function would be with a `useRef` hook, giving the dispatch function. I also think, all the functions such as `insert()`, `remove()`, etc.. should be exported and made available on the library.

Access to all those "behind the scenes" will make the library much more customizable.
