### ISSUE TITLE
Delete option is duplicating elements

### ISSUE THREAD

**Issue by sra-013** [measuredco/puck#191]
Hi, the delete option seems to be duplicating elements on the UI. Is it just me or is this a known issue?

**Comment by chrisvxd** [comment]
Hey @sra-013. I can't reproduce this on my end.

Can you share more information?

* Version
* Browser
* Operating system

**Comment by sra-013** [comment]
Yes, sure

Version - ^0.6.2
Browser - Chrome
Operating system - MacOS Monterey (M1)

**Comment by chrisvxd** [comment]
@sra-013 There have been a few releases since `0.6.2`. Can you try `0.10.0` and let me know if the issue still persists?

**Comment by sra-013** [comment]
Hi Chris, i tried and unfortunately yes, the issue still persists even with the newer version

**Comment by chrisvxd** [comment]
@sra-013 thats highly unusual. Can you reproduce the bug on the official demo? https://puck-editor-demo.vercel.app/edit

If not, can you share some code to reproduce?

**Comment by chrisvxd** [comment]
Closing this as unable to reproduce. @sra-013 please ping me if you can recreate in the demo above.
