### ISSUE TITLE
add categories

### ISSUE THREAD

**Issue by PCosta1990** [measuredco/puck#193]
hi

I added categories in config and  display this error 
`Type '{ root: { render: ({ children, editMode }: RootProps) => JSX.Element; }; categories: { layout: { components: string[]; }; typography: { components: string[]; }; interactive: { title: string; components: string[]; }; }; components: { ...; }; }' is not assignable to type 'Config<Props, RootProps>'.
  Object literal may only specify known properties, and 'categories' does not exist in type 'Config<Props, RootProps>'.ts(2322)`

my vesion is 0.10.0 
is there any other file that i need to change  

my config type is 
`
type Config<Props extends {
    [key: string]: any;
} = {
    [key: string]: any;
}, RootProps extends DefaultRootProps = DefaultRootProps> = {
    components: {
        [ComponentName in keyof Props]: ComponentConfig<Props[ComponentName], Props[ComponentName]>;
    };
    root?: ComponentConfig<RootProps & {
        children: ReactNode;
    }, Partial<RootProps & {
        children: ReactNode;
    }>>;
};
`

**Comment by xaviemirmon** [comment]
Hi @PCosta1990 👋,

This will be because the categories feature has yet to be released but will once 0.11.0 is ready.  In the meantime, you can install a canary [0.11.0-canary.4613df4](https://www.npmjs.com/package/@measured/puck/v/0.11.0-canary.4613df4), and that should be able to get it working!

**Comment by chrisvxd** [comment]
Yes, @xaviemirmon is right. This hasn't been released yet. I'm working on a few more changes to adaptors before canary is stable and I can do a release.
