### ISSUE TITLE
Make Puck more composable

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#224]
We should consider supporting composable layouts for Puck, enabling more sophisticated implementations.

For example, as part of the docs site, we are reimplementing Puck with a custom layout for interactive examples. This should be supported OOTB.

### Default - no children

If no children are passed to `<Puck>`, the default layout will be used.

### Render children

When the user defines children, the user can take over the Puck layout.

```tsx
export const Editor = () => {
  return <Puck>{({ appState, dispatch }) => (
    <>
      <Puck.Preview />
      <Puck.Form />
    </>
  )}</Puck>
}
```

Should also support direct children, instead of render children

```tsx
export const Editor = () => {
  return <Puck>
    <Puck.Preview />
    <Puck.Form />
  </Puck>
}
```

### usePuck hook
Which can be combined with a `usePuck` hook to access the context

```tsx
export const MyComponent = () => {
  const { dispatch } = usePuck();

  return <button onClick={() => dispatch()}>Click me</button>
}
```

**Comment by nicolas-angelo** [comment]
I def like the idea of a Puck ctx hook and added composability features.

It would be great to get control of the Preview UI so I could do things like update preview screen size w/ custom viewport toggle buttons (maybe being able to add tw container query classes on the Preview root?)

Additionally I'd want more control over rendering custom component lists, toggling visibility on sections like "Outline"...

and having greater control over the dispatch API in components outside of the plugins area. (I'm currently using portals and positioning hacks to achieve this)

**Comment by chrisvxd** [comment]
Nearly there implementing this in #265. Proposed documentation: https://puck-docs-j9sbcd36i-measured.vercel.app/docs/extending-puck/custom-interfaces
