### ISSUE TITLE
Improve responsive behaviour

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#225]
Puck currently has several responsive issues making it difficult to use on mobile.

Ideally, Puck will be fully responsive. The underlying drag-and-drop implementation is already mobile friendly, so there are mainly CSS issues outstanding.

**Comment by EarthlingDavey** [comment]
If you could share a mobile mockup, or even describe it, then I could have a shot at this.

**Comment by chrisvxd** [comment]
Hey @EarthlingDavey! I believe @monospaced is already working on this one, but I wanted to track it for visibility :)

**Comment by EarthlingDavey** [comment]
Ah, got ya.
