### ISSUE TITLE
Add docs site

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#24]
Let's use this issue to crib out structure for a proper docs site

**Comment by xaviemirmon** [comment]
@chrisvxd If you have something in MD/MDX, I'd happily raise PRs bits where I can.

**Comment by chrisvxd** [comment]
Thanks @xaviemirmon!

We'll definitely end up using MD / MDX. Suspect probably go with https://nextra.site to keep things in the Next ecosystem for now.

**Comment by chrisvxd** [comment]
Done in #237
