### ISSUE TITLE
"Add Page" in the top bar allows users to dynamically create pages.

### ISSUE THREAD

**Issue by prashanthvdckap** [measuredco/puck#271]
"Add Page" in the top bar allows users to dynamically create pages with their own URLs.

**Comment by hddananjaya** [comment]
@chrisvxd Is this something that we are planning to support and are there workarounds for now?

**Comment by chrisvxd** [comment]
This is actually a user-land issue, rather than a Puck issue. We could consider adding it to the recipes, but I wouldn't consider it Puck core.

**Comment by dohomi** [comment]
Hey guys, I am curious how this issue could be solved as this is one requirement of my use case.
