### ISSUE TITLE
puck.config.tsx not watched by Remix recipe

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#273]
## Description

Currently, if the user changes their `puck.config.tsx` in the remix recipe, they must reboot the server.

This is because remix only watches the contents of `/app` by default.

### Option 1

Add `puck.config.tsx` to [`watchPaths`](https://github.com/remix-run/remix/issues/1601#issuecomment-1785020576)

### Option 2

Move `puck.config.tsx` within the `/app` directory.

**Comment by chrisvxd** [comment]
FYI @EarthlingDavey, if you ever do another pass on the remix recipe :)

**Comment by chrisvxd** [comment]
I think I'd go with option 1!

**Comment by EarthlingDavey** [comment]
Like last time, should I make a PRs into the main branch?

**Comment by chrisvxd** [comment]
Closed by #279. Thanks @EarthlingDavey!
