### ISSUE TITLE
Orderable outline/layers

### ISSUE THREAD

**Issue by jperasmus** [measuredco/puck#308]
Feature request:

It would be great if the items in the `<Outline />` component were orderable via drag-and-drop. That way a user would be able to quickly move bigger blocks around without needing to do it in the preview frame.

Another smaller request is to show the top-level page in the Outline for easy selection.

**Comment by chrisvxd** [comment]
Good request! Been on our radar for a while but has never been prioritised.

I think drag-and-drop between a given DropZone should be easy enough, but drag-and-drop between DropZones is more challenging. We could possibly phase the implementation.

**Comment by jperasmus** [comment]
Also, you would want the items to respect the "allow" and "disallow" props on dropzones (if dropping inside a component).

**Comment by chrisvxd** [comment]
Closing as duplicate of #126
