### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by seeranjeeviramavel** [measuredco/puck#312]
I am encountering errors consistently when starting my create-react-app. Could you please provide guidance on how to resolve this issue?

Module not found: Error: Can't resolve 'crypto'

-     node: v18.17.0
-     react: v18.2.0

![Screenshot (86)](https://github.com/measuredco/puck/assets/114507428/047bb250-4d6b-45b6-9967-77a89007decc)

My CodeSandbox:
https://codesandbox.io/p/devbox/react-puck-test-psj37t?file=%2Fsrc%2FEditor.jsx

**Comment by chrisvxd** [comment]
This is a duplicate of #112. I'm going to remove crypto in 0.13.1.

**Comment by seeranjeeviramavel** [comment]
> This is a duplicate of #112. I'm going to remove crypto in 0.13.1.

Great! Thank You for resolving this :)

**Comment by chrisvxd** [comment]
Thanks for closing the issue @seeranjeeviramavel!
