### ISSUE TITLE
Expose history to `usePuck` hook

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#317]
## Description

The `history` object should be exposed to the `usePuck` hook, along with `forward()` `back()`, `hasFuture` and `hasPast`.

**Comment by prashanthvdckap** [comment]
Hi @chrisvxd Thanks for keeping track. When will this feature go live?

**Comment by chrisvxd** [comment]
Hi @prashanthvdckap - suspect not until next month at the earliest as we have other items in our queue. Feel free to contribute the feature if you have the time.

**Comment by prashanthvdckap** [comment]
Hi @chrisvxd  i have exposed history in usePuck hook. please review.
Thanks

**Comment by chrisvxd** [comment]
Closed in #342
