### ISSUE TITLE
general

### ISSUE THREAD

**Issue by Harish-78** [measuredco/puck#322]
How to add the view Page button into the puck editor.

**Comment by chrisvxd** [comment]
Hi @Harish-78 - the View Page button can be done using [overrides](https://puckeditor.com/docs/extending-puck/custom-interfaces#ui-overrides).

Specifically, you want the [`headerActions`](https://puckeditor.com/docs/api-reference/overrides/header-actions) override:

```tsx
const overrides = {
  headerActions: ({ children }) => (
    <>
      <button>Click me</button>
      {children}
    </>
  ),
};
 
export function Editor() {
  return (
    <Puck
      // ...
      overrides={overrides}
    />
  );
}
```
