### ISSUE TITLE
Prop to rename or pass custom component for  Publish Button 

### ISSUE THREAD

**Issue by sagarchoudhary96** [measuredco/puck#323]
Is it possible to give option to rename the Publish Button we have in Puck Editor Menubar. For E.g if it needs to be renamed to `Save` or something else and change icon or it's color etc . i think the best way could be to  give ability to pass Custom Button which can be rendered in Place of Publish Button.

<img width="180" alt="Screenshot 2024-01-11 at 8 20 01 PM" src="https://github.com/measuredco/puck/assets/16102594/a977f302-26bf-4fce-a62d-1600db10217a">

**Comment by chrisvxd** [comment]
Hi @sagarchoudhary96 - please see #310

**Comment by sagarchoudhary96** [comment]
@chrisvxd  checked it but not sure how still it can be done. Also is there way to programatically trigger `onPublish` call. I want to add keyboard shortcut which triggers the `onPublish` method of the puck.

**Comment by chrisvxd** [comment]
I think #310 is stale, so I'll need to revisit at some point.

`onPublish` just takes the current data and fires a callback. You can easily recreate this behaviour with the `usePuck` hook to get the latest data.

**Comment by sagarchoudhary96** [comment]
Yep that works  , Thanks :)
