### ISSUE TITLE
Undo/redo buttons do not inherit interactive state colors from `IconButton`

### ISSUE THREAD

**Issue by monospaced** [measuredco/puck#330]
Because [color styles are being applied at the SVG stroke level](https://github.com/measuredco/puck/blob/22a41823559d36fd06842496d59788004b316797/packages/core/components/MenuBar/index.tsx#L64), the undo/redo buttons in `MenuBar` do not consistently apply the default interactive `:hover`/`:active` color styles (which should be inherited from `IconButton`). 

See [sidebar toggle buttons](https://github.com/measuredco/puck/blob/22a41823559d36fd06842496d59788004b316797/packages/core/components/Puck/index.tsx#L430) for the correct implementation (styles applied to a parent element). This way, we are able to manage different default colors (dark/light grey, depending on state), whist still allowing the interactive states to be inherited.

**Comment by cmutaledev** [comment]
Good day, I am pretty new to contributing to oss, I thought this would be a good start for me as I get accustomed to the procedures. I have a small fix for this, basically removing the `stroke` styling on the chevron svg's. Wanted to confirm if this is a good move, as I see that you have a different color for disabled IconButton (--puck-color-grey-07) whereas the stroke on the chevron's is (--puck-color-grey-08) will this be an issue or it doesn't matter?

**Comment by monospaced** [comment]
@cmutaledev I think it would make sense to make those disbaled states consistent `--puck-color-grey-07` would be the one to use 👍🏻. The chevron should also receive link hover colours, etc. essentially the exact same state behaviour as the sidebar toggle buttons.

**Comment by xaviemirmon** [comment]
I've created a fix for this on PR #551
