### ISSUE TITLE
Error while loading puck editor

### ISSUE THREAD

**Issue by sagarchoudhary96** [measuredco/puck#339]
<img width="1431" alt="Screenshot 2024-01-24 at 12 04 04 AM" src="https://github.com/measuredco/puck/assets/16102594/b6626454-35a3-489f-81f1-c459776afa1f">
<img width="434" alt="Screenshot 2024-01-24 at 12 04 14 AM" src="https://github.com/measuredco/puck/assets/16102594/e574e3f5-9943-4e97-b0e3-af466c308a89">

i'm seeing this error while loading puck editor at `const flatcontent = ` line. it's happening when the data has any component which is not present in the component config passed to puck editor  @chrisvxd. in previous versions this error was not there.

**Comment by chrisvxd** [comment]
@sagarchoudhary96 Can you share a minimal config to reproduce, please?

**Comment by sagarchoudhary96** [comment]
i'll try to create one, but yeah if the initialData have value for some component type and that component is not in the componentData  passed to puck editor, it will happen.
