### ISSUE TITLE
Unexpected behavior for 'Enter' keypress in focused input

### ISSUE THREAD

**Issue by charismental** [measuredco/puck#345]
https://github.com/measuredco/puck/assets/39839237/ddb5ad50-2408-40d3-87af-e0e994df3fe4

I noticed while editing some components that if I pressed the enter key, it seemed to have a different element focused than the input that I was typing within. In particular, hitting enter when adjusting column span number for columns component, it would delete one of the columns.

**Comment by chrisvxd** [comment]
Thanks @charismental. Seems like a valid bug. Triaged and marked as ready.
