### ISSUE TITLE
How can I zoom In and Out the preview?

### ISSUE THREAD

**Issue by martinogarrizzo5** [measuredco/puck#350]
Hi,
I was interested if there were any possibilities to make the preview zoomable.
I'm trying to make a Figma like experience of navigation inside the editor.
Thanks

**Comment by chrisvxd** [comment]
Hi @martinogarrizzo5. What kind of zoom are you looking for? Figma-style infinite zoom (with pinch-to-zoom), or a `+`/`-` button zoom experience, kinda like dev tools?

**Comment by martinogarrizzo5** [comment]
Hi, 
I think either one or the other solutions can be good. What do you suggest?
Thanks

**Comment by chrisvxd** [comment]
This should be landing in #353.

**Comment by chrisvxd** [comment]
Closing as #353 is now merged and will be released in `v0.14.0`
