### ISSUE TITLE
Inline Editing (Cannot get current id of a custom text component's instance for setting id while dispatching replace action in the component.)

### ISSUE THREAD

**Issue by Roshan54321** [measuredco/puck#351]
#### Objective:
Inline Editing

#### Main issue:
The two text components have same id( actually, no id at all), so they are both being selected at once even if I select one among them.
![image](https://github.com/measuredco/puck/assets/61241132/23aca184-f269-4b7f-8588-6e755898d56c)

#### How to reproduce?
- Drag n drop two text components.
- Change the content of a text component.
- Change the content of another text component.
- Click on one among the text components.

#### Text Component
```
import React, { useRef } from "react";
import { ComponentConfig, usePuck } from "@measured/puck";
import { Type } from 'react-feather'
import { ColorPickerField } from "../puck_fields/ColorPickerField"
import useIsEditingPath from "../../../lib/usEditingPath"

export type TextProps = {
    align: "left" | "center" | "right";
    text?: string;
    padding?: number;
    size?: number;
    color: any;
    maxWidth?: number;
};

export const Text: ComponentConfig<TextProps> = {
    fields: {
        text: { type: "textarea", label: "Text" },
        size: { type: "number", label: "Size" },
        align: {
            type: "select",
            options: [
                { label: "Left", value: "left" },
                { label: "Center", value: "center" },
                { label: "Right", value: "right" },
            ],
            label: "Align"
        },
        color: { ...ColorPickerField, label: "Color" },
        padding: { type: "number", label: "Padding" },
        maxWidth: { type: "number", label: "Max Width" },
    },
    defaultProps: {
        align: "left",
        text: "Text",
        padding: 24,
        size: 16,
        color: { color: "#000000" },
    },
    render: ({ color, align, size, maxWidth, padding, text }) => {
        const { isEdit } = useIsEditingPath()
        const { appState, dispatch } = usePuck();

        const onChange = (e: any) => {
            e.preventDefault();
            const { ui } = appState;
            const { itemSelector } = ui;

            dispatch({
                type: "replace",
                destinationIndex: itemSelector.index,
                destinationZone: itemSelector.zone,
                data: { props: { color, align, size, maxWidth, text: e.target.textContent }, type: "Text" },
            });

        }

        return (
            <div suppressContentEditableWarning contentEditable={isEdit} {...(isEdit ? { onInput: onChange } : {})}
                style={{
                    color: color.color,
                    textAlign: align,
                    width: "100%",
                    fontSize: `${size}px`,
                    fontWeight: 300,
                    maxWidth,
                    overflowWrap: "break-word",
                }}
            >
                {text}
            </div>
        );
    },
};
```

#### Text Component Instance's data before editing content:
```
      {
        "type": "Text",
        "props": {
          "align": "left",
          "text": "Text",
          "padding": 24,
          "size": 16,
          "color": {
            "color": "#000000"
          },
          "id": "Text-79fe516b-cb1b-47f9-98df-f9af293fb034"
        }
```

#### Text Component Instance's data after editing content:
```
      {
        "props": {
          "align": "left",
          "text": "Text",
          "padding": 24,
          "size": 16,
          "color": {
            "color": "#000000"
          },
        },
        "type": "Text"
      }
```

#### What could be done?
```
            dispatch({
                type: "replace",
                destinationIndex: itemSelector.index,
                destinationZone: itemSelector.zone,
                data: { props: { color, align, size, maxWidth, text: e.target.textContent }, type: "Text", id: currentId },
            });
```
_Getting currentId is the problem._

**Comment by chrisvxd** [comment]
Hi @Roshan54321. Puck exposes the You should be able to get the current ID from the `id` prop that's passed into your `render` function. Let me know if that helps.

**Comment by Roshan54321** [comment]
> Hi @Roshan54321. You should be able to get the current ID from the `id` prop that's passed into your `render` function. Let me know if that helps.

Thank you @chrisvxd . I missed it completely.

**Comment by chrisvxd** [comment]
@johannbuscail I don't think we currently provide the _component ID_ on custom fields or field overrides, but we do provide the _field ID_ under the `id` prop. What's your use case?

**Comment by Roshan54321** [comment]
@chrisvxd how can I override the array or the object fields?

**Comment by chrisvxd** [comment]
@Roshan54321 you can either use the [`custom` field type](https://puckeditor.com/docs/extending-puck/custom-fields) or override the `array`/`object` field types using [UI overrides](https://puckeditor.com/docs/extending-puck/custom-interfaces#field-type-override-example).

**Comment by Roshan54321** [comment]
@chrisvxd Overriding array/object using UI overrides looks quite tricky. I was wondering how can I know the type of each field of the children and render each one that can possibly come, I mean it can be anything, isn't it?. Custom field is straightforward as I get to implement everything by myself. I just wanted to change the designs of the array/object types. Is there an efficient way of doing that?

**Comment by chrisvxd** [comment]
I'm not sure exactly what changes you're looking to make, but you can do this using UI overrides:

```tsx
import { Puck } from "@measured/puck";
 
export function Editor() {
  return (
    <Puck
      // ...
      overrides={{
        fieldTypes: {
          array: ({ name, onChange, value }) => (
            <div>My Array Field</div>
          ),
        },
      }}
    />
  );
}
```

If you want to just modify the _theme_ for the original UI, you'll have to wait for #139.
