### ISSUE TITLE
Issue adding array for root props

### ISSUE THREAD

**Issue by PrinceAdeleke** [measuredco/puck#358]
When adding root level props of type array, it doesn't allow the user to populate the props using the Puck editor.

Config:
```
const config = {
  categories: {
    navigation: {
      components: ['Navigation']
    }
  },
  root: {
    fields: {
      title: { type: 'text' },
      tags: {
        type: 'array',
        arrayFields: {
          id: { type: 'text' },
        }
      },
    },
    render: ({ children }) => {
      return (
        <div>{children}</div>
      )
    },
  },
  components: {
    HeadingBlock: {
      fields: {
        title: {
          type: "text",
        },
      },
      render: ({ title }) => {
        return <h1>{title}</h1>;
      },
    },
  },
};
```

<img width="287" alt="img" src="https://github.com/measuredco/puck/assets/9345337/ff170758-eb2d-42c4-b212-dfa1c4b2c8ac">

**Comment by 4leite** [comment]
There is an error in the above config (but that shouldn't cause the issue you are seeing anyway).
` components: ['Navigation']`
should be:
`components: ['HeadingBlock']`

I was not able to reproduce your error with a fresh app from the next recipe and your config. Can you link a minimal reproducible example?

**Comment by PrinceAdeleke** [comment]
> There is an error in the above config (but that shouldn't cause the issue you are seeing anyway). ` components: ['Navigation']` should be: `components: ['HeadingBlock']`
> 
> I was not able to reproduce your error with a fresh app from the next recipe and your config. Can you link a minimal reproducible example?

Yep, copy and pasted but edited in the editor to remove some stuff I was doing.
Here's an example replicating the issue: https://github.com/PrinceAdeleke/vite-root-prop-issue

I did notice that if initialProps is not set it works, but if set but root and data is empty then it doesn't work. It will add an entry for the data but the UI editor for the new object that was added will not show.

**Comment by 4leite** [comment]
Ah yep that make sense, for now you'll need to assign the initialData, eg:
  root: { props: { tags: [] } }
