### ISSUE TITLE
Make `InputOrGroup` accessible through library.

### ISSUE THREAD

**Issue by johannbuscail** [measuredco/puck#365]
Creating complex 'custom' fields by hand is currently a challenging task. Especially most of the times, we only want to add a small button the the field and that requires rebuilding everything from scratch.

Having access to the 'InputOrGroup' element would significantly streamline this process, allowing for the reuse of the library's existing structures. 

This would enable a more straightforward way to add complex structures to the sidebar fields, enhancing the user experience and development efficiency.

This is related to https://github.com/measuredco/puck/issues/361

**Comment by chrisvxd** [comment]
@johannbuscail great suggestion. We will likely want to rename the component (possibly to `Puck.Field` - open to suggestions).

This will increase the API surface area for breaking changes.

**Comment by chrisvxd** [comment]
Closing in favour of #463
