### ISSUE TITLE
Enable override of publish button

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#378]
If using the default header, there is no way to override the publish button. Specifically, the headerActions override does not provide any mechanism to change any existing controls, instead only allowing users to inject new controls.

### Proposal 1

Add new `publishLabel` API to quickly change the label of the publish button

### Proposal 2

When using the `headerActions` override, don't render the legacy actions, instead passing them in as `children` to the override.

### Proposal 3

Add explicit override for the Publish button

**Comment by chrisvxd** [comment]
@bwat-dev I think adding more comprehensive documentation custom interfaces, alongside API changes, would be a great idea.

**Comment by bwat-dev** [comment]
@chrisvxd being able to override just the header shouldn't be too complicated if we stick to the same logic :

```jsx
<Puck
    config={config}
    data={initialData}
    overrides={{
        header: () => <CustomHeader onPublish={customPublishHandler} />,
    }}
/>
```
But the risk is to develop an overly complex solution that tries to do too many things. ^^

**Comment by chrisvxd** [comment]
@hire2inspire2023 If you download the latest canary build ([0.15.0-canary.dd7051e](https://www.npmjs.com/package/@measured/puck/v/0.15.0-canary.dd7051e)), you can use the `headerActions` override to implement a new button:

```tsx
import { Puck, Button } from "@measured/puck";

function Editor() {
  return (
    <Puck
      overrides={{
        headerActions: () => <Button onClick={() => {}}>My Button</Button>,
      }}
    />
  );
}
```

Docs: https://puckeditor.com/v/canary/docs/api-reference/overrides/header-actions
