### ISSUE TITLE
Add Used by Section to Readme

### ISSUE THREAD

**Issue by William-McGonagle** [measuredco/puck#381]
If you would like a used-by section in the Readme, Puck is now being used in production by Georgetown Disruptive Tech's [ReRoto](https://reroto.com/).

**Comment by chrisvxd** [comment]
Oh that's awesome @William-McGonagle.

We currently have a "Made with Puck" section in [our Discord](https://discord.gg/D9e4E3MQVZ), but I'd love to also add something more public (like the README or even the docs website).

**Comment by William-McGonagle** [comment]
Would you like me to put together a pull request for it to make your life a bit easier? I can add some of the other projects from the Discord as well.

**Comment by chrisvxd** [comment]
Hey @William-McGonagle - decided this belongs in the [awesome-puck repo](https://github.com/measuredco/awesome-puck), alongside plugins and other community packages. I've added ReRoto for you - hopefully that works!

**Comment by William-McGonagle** [comment]
Thank you @chrisvxd - have a wonderful day.
