### ISSUE TITLE
How to set max & min height / width to preview / page

### ISSUE THREAD

**Issue by skielder** [measuredco/puck#384]
Is there a way to set a max & min height / width to the page / preview?

I tried the overwrite method, but didn't really get what I wanted.

**Comment by chrisvxd** [comment]
This is only possible via the latest canary build, which supports viewports, or if you're implementing a [custom interface](https://puckeditor.com/docs/extending-puck/custom-interfaces).

If you're using the latest canary build and a default interface, you can use the [`viewports` API](https://puckeditor.com/v/canary/docs/api-reference/components/puck#viewports) to control this. If you're using a custom interface, set the width/height of the element wrapping the `<Puck.Preview />` component.

**Comment by chrisvxd** [comment]
You can see canary builds [on npm](https://www.npmjs.com/package/@measured/puck?activeTab=versions).

Latest is [0.14.0-canary.26bc4ff](https://www.npmjs.com/package/@measured/puck/v/0.14.0-canary.26bc4ff). If you're installing it, you need to target that particular version in NPM (i.e. avoid `^` and `~`)

```json
{
  "dependencies": {
    "@measured/puck": "0.14.0-canary.26bc4ff"
  }
}
```

We're also close to releasing `0.14.0`.
