### ISSUE TITLE
DropZone doesn't renders in ui components library

### ISSUE THREAD

**Issue by SicParv1sMagna** [measuredco/puck#406]
DropZone doesn't renders in puck editor after replacing components in ui-library. I tried to make it with column component from [Demo](https://github.com/measuredco/puck/tree/main/apps/demo). I had created two components: one inside of ui-library, second inside of the project, both has DropZones. Ui-library has been linked using `npm link`.
Result: DropZone renders correctly only in second case (inside of the project with consturctor, correctly means, that I can drag other components inside of DropZone), in first case this functionality doesn't work.

My steps:
1. Creating next app, using recipe: `npx create-puck-app my-ap`.
2. Installing dependencies.
3. Adding "Columns" inside of next app and renaming it to "Columns1".
4. Creating ui-library using vite and adding "Columns" inside of it, then renaming "Columns" to "Columns2".
5. Building ui-library.
6. Linking ui-library to next app, using `npm link pseudo-ui-new-lib@0.0.0`, inside of constructor.
7.  Starting constructor using `npm run dev`.
8. Adding "Column1" to constructor and "Column2".

Difference:

I noticed that while I importing component from ui-lib, it doesn't have this div inside of it: `<div class="_DropZone_w4btq_1 _DropZone--isDisabled_w4btq_28 _DropZone--isAreaSelected_w4btq_26"><div data-rfd-droppable-id="Columns1-d2af8940-1c01-4ff9-a40d-54bc01126b08:column-0" data-rfd-droppable-context-id=":r0:" class="_DropZone-content_w4btq_10" id="Columns1-d2af8940-1c01-4ff9-a40d-54bc01126b08:column-0"></div></div>`

![image](https://github.com/measuredco/puck/assets/92353726/c75b2f01-a266-44d3-8838-627ae59cb516)

UI-Library has been created according to this [guide](https://dev.to/receter/how-to-create-a-react-component-library-using-vites-library-mode-4lma)
You can see my code here: [Constructor](https://github.com/SicParv1sMagna/puck-constructor) and [UI-Library](https://github.com/SicParv1sMagna/ui-lib)

**Comment by haidv1992** [comment]
i have same issue when run demo in app and use packages

![image](https://github.com/user-attachments/assets/da45ada1-8b81-4997-bd0b-60f32d60473b)

error in editor not show column

![image](https://github.com/user-attachments/assets/d58a6e4a-301a-43c9-84b5-f8a02adfce4e)

**Comment by chrisvxd** [comment]
@haidv1992 Cloning the repo is not recommended. Please use `create-puck-app` for creating a project with access to the robust public API.
