### ISSUE TITLE
Iframe enabled false has a UI issue

### ISSUE THREAD

**Issue by Sahak885** [measuredco/puck#412]
1. npx create-puck-app my-app
2. add on Puck component iframe={{enabled: false}}

Google Chrome 121.0.6167.85

![image](https://github.com/measuredco/puck/assets/81028706/2f21aecb-1ec8-47e9-8a88-4635c5f88a23)

**Comment by chrisvxd** [comment]
I don't know what is up with your environment but I can't reproduce this one either 😅  Which OS are you running? Any errors in console?

This could be an issue with DropZones not mounting, similar to #411.

<img width="1624" alt="image" src="https://github.com/measuredco/puck/assets/985961/5eff3dac-77ed-4647-9dd7-5d4eb3d4beeb">

**Comment by Sahak885** [comment]
![image](https://github.com/measuredco/puck/assets/81028706/edf0ceab-1179-4704-85fd-e6641293f017)

**Comment by Sahak885** [comment]
OS
`Linux name-System-Product-Name 5.15.0-101-generic #111~20.04.1-Ubuntu SMP Mon Mar 11 15:44:43 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Sahak885** [comment]
@chrisvxd 
Loom video: https://www.loom.com/share/591f0f0fd2064f55b4359484e64e0574

**Comment by Sahak885** [comment]
![image](https://github.com/measuredco/puck/assets/81028706/fbdb57db-ca30-4168-abf3-8eb309ff30d4)

**Comment by chrisvxd** [comment]
Fix available in `0.14.2-canary.64303c8`.
