### ISSUE TITLE
Loading Puck CMS in Iframe getting getBoundingClientRect error

### ISSUE THREAD

**Issue by prashanthvdckap** [measuredco/puck#428]
Loading Puck CMS in Iframe (loading entire CMS page in Iframe) getting getBoundingClientRect error

Steps to reproduce

1. ` <iframe src={"https://demo.puckeditor.com/edit"}  frameBorder="0" />`

2. drag the component. 
3. check the console

![image](https://github.com/measuredco/puck/assets/96864283/74a4042d-0553-476d-a8cd-d7a0eed7f979)

**Comment by chrisvxd** [comment]
Fixed in 0.14.2-canary.23db292

**Comment by prashanthvdckap** [comment]
Thanks @chrisvxd its working now
