### ISSUE TITLE
Build failing with Cannot find module '@measured/puck/types/Config' and Collecting page data

### ISSUE THREAD

**Issue by maantjemol** [measuredco/puck#46]
Hi!
I'm running into a few errors when trying to build the next app:
The first one is a type error in `./app/[...puckPath]/page.tsx`:
```
Type error: Cannot find module '@measured/puck/types/Config' or its corresponding type declarations.

  3 | import resolvePuckPath from "./resolve-puck-path";
  4 | import { Metadata } from "next";
> 5 | import { Data } from "@measured/puck/types/Config";
    |                      ^
  6 | 
  7 | export async function generateMetadata({
  8 |   params,
```
I think this can be fixed by changing:
```typescript
import { Data } from "@measured/puck/types/Config";
// to ->
import { Data } from "@measured/puck";
```
and changing line 27 from:
```typescript
return {
  title: data?.page?.title, // Property 'page' does not exist on type 'Data'
};
// to ->
return {
  title: data?.root?.title, 
};
```
This gets me further into the build process, but it errors out on the `Collecting page data` step:
```
pnpm run build

> test_app_puck_v2@1.0.0 build /Users/maantje/programmeren/Full webapps/test_app_puck_v2
> next build

- info Creating an optimized production build  
- info Compiled successfully
- info Linting and checking validity of types  
- info Collecting page data  
[    ] - info Generating static pages (0/3)TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: AggregateError
      at internalConnectMultiple (node:net:1111:18)
      at afterConnectMultiple (node:net:1663:5)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: AggregateError
      at internalConnectMultiple (node:net:1111:18)
      at afterConnectMultiple (node:net:1663:5)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}

Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11576:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
- info Generating static pages (3/3)

> Export encountered errors on following paths:
        /page: /
```
I also tried with yarn, which gave me the same results. 

## Steps to reproduce:
1. Run `npx create-puck-app` and use default options
2. Open in code editor and fix type error according to code above
3. Run `npm run dev` or `yarn dev`
4. Create the `/` page and give it a title and heading with random words
5. Close the dev server and run `npm run build` or `yarn build`

I found this(https://stackoverflow.com/questions/74165121/next-js-fetch-request-gives-error-typeerror-fetch-failed) which can maybe help, but I didn't really figure it out. I think it has something to do with the fetch to localhost:3000 in `./app/[...puckPath]/page.tsx`.

edit: just occurred to me that this should probably be 2 different issues

**Comment by chrisvxd** [comment]
Sorry about the issues you've been having with the generator. It's clearly lagged behind the core functionality somewhat as `root` is pretty dated now. #10 should help.

Don't worry about separating the issues.

I've seen the fetch error before. I'll patch the first couple of issues in the generated code and investigate the second.

**Comment by maantjemol** [comment]
Thanks! No problem! I think the project is awesome, and I've been searching for a simple CMS type system that is cheap to host and open source for next, and this is by far the best thing I've seen so far, so I'm happy to wait :).

**Comment by chrisvxd** [comment]
Looks like the page.tsx code generated is invalid. Because we're using an API to read the data served from the same application, Next.js is trying to call itself when generating the static pages with calls to `http://localhost:3000/api/puck`.

We can fix this by reading the database.json directly.

Here's an updated version that should work:

```tsx
import { Client } from "./client";
import { notFound } from "next/navigation";
import resolvePuckPath from "./resolve-puck-path";
import { Metadata } from "next";
import { Data } from "@measured/puck";
import fs from "fs";

// Replace with call to your database
const getPage = (path: string) => {
  const allData: Data | null = fs.existsSync("database.json")
    ? JSON.parse(fs.readFileSync("database.json", "utf-8"))
    : null;

  return allData ? allData[path] : null;
};

export async function generateMetadata({
  params,
}: {
  params: { puckPath: string[] };
}): Promise<Metadata> {
  const { isEdit, path } = resolvePuckPath(params.puckPath);

  if (isEdit) {
    return {
      title: "Puck: " + path,
    };
  }

  return {
    title: getPage(path),
  };
}

export default async function Page({
  params,
}: {
  params: { puckPath: string[] };
}) {
  const { isEdit, path } = resolvePuckPath(params.puckPath);

  const data = getPage(path);

  if (!data && !isEdit) {
    return notFound();
  }

  return <Client isEdit={isEdit} path={path} data={data} />;
}
```

**Comment by maantjemol** [comment]
It works!

**Comment by chrisvxd** [comment]
You'll likely encounter another problem now because Next's generating the static pages at build time, which means the pages won't update if you re-publish. Will need to switch to dynamic rendering, ISSG , or prep the pages before builds.

**Comment by chrisvxd** [comment]
This should give you a best-of-both-worlds solution with pages that generate on-demand and then cache heavily until we create a new page

Update `/app/api/route.ts`:

```tsx
import { revalidatePath } from "next/cache";
import { NextResponse } from "next/server";
import fs from "fs";

export async function POST(request: Request) {
  const data = await request.json();

  const existingData = JSON.parse(
    fs.existsSync("database.json")
      ? fs.readFileSync("database.json", "utf-8")
      : "{}"
  );

  const updatedData = {
    ...existingData,
    ...data,
  };

  fs.writeFileSync("database.json", JSON.stringify(updatedData));

  // Purge Next.js cache
  revalidatePath(data.path);

  return NextResponse.json({ status: "ok" });
}
```
