### ISSUE TITLE
Add API Access for Fields in Custom Array Component

### ISSUE THREAD

**Issue by ab5y** [measuredco/puck#466]
We are trying to build an `Array` type component which comes with some default fields but can can be extended with some more fields the user chooses. 

But we would also like to be able to remove the default fields the `Array` component comes with.

The new fields can be added and deleted from the right side `properties` UI. We tried our best to find a way to insert our default fields to this section, but we are yet to find a way to do that. 

Any suggestions on how we can achieve this based on existing capabilities would also be highly appreciated!

**Comment by chrisvxd** [comment]
Hi @ab5y - the Dynamic Fields API added in #280 is available in the canary build, and might help your use case. Let me know if that helps.
