### ISSUE TITLE
Feature Custom Components with Zoom-In Zoom-Out

### ISSUE THREAD

**Issue by abhimanyuDA** [measuredco/puck#470]
Please create Custom Components with Zoom-In Zoom-Out and Responsive Settings. If Possible, in the same look as it looks in Default View [Left Sidebar, Main Preview and Right Sidebar]

**Comment by chrisvxd** [comment]
Viewport functionality should be handled by the user when using custom interfaces: https://puckeditor.com/docs/integrating-puck/viewports#controlling-viewports-with-custom-interfaces
