### ISSUE TITLE
Adding "Custom Props" Type to Base Field Type

### ISSUE THREAD

**Issue by OsamuBlack** [measuredco/puck#471]
Puck editor allows us to override the individual fields using **override -> fieldTypes**. I have a small recommendation regarding this. Add custom props type to `base field` in the `core/types.ts` file like this. 

```ts
type BaseField = {
    label?: string;
    customProps: {
      [key: string]: any;
    }
};
```

This allows users to extend the existing fields for all sorts of requirements. For example, a user can extend the text field to support email or URL sub-types.

```ts
email: {
    type: "text",
    label: "Title",
    customProps: {subType: "email"}
}
```
and use it in the overrides to apply their own implementations.

Puck already passes the field props to the overrides but you need to typecast the modified fields.
```ts
email: {
    type: "text",
    label: "Title",
    customProps: {subType: "email"}
} as TextField
```

**Comment by chrisvxd** [comment]
Hi @OsamuBlack! Is there a reason you couldn't use `custom` field types for this?
