### ISSUE TITLE
Custom Toolbar

### ISSUE THREAD

**Issue by asepmedia** [measuredco/puck#477]
Hi, First of all, thank you for making this, I want to ask if you want to make a custom toolbar like this, is it possible?

![image](https://github.com/measuredco/awesome-puck/assets/38859211/11a67889-61d5-4f20-b40a-90132b702d2c)

For example: I added a custom Number / Bullet List

**Comment by chrisvxd** [comment]
@asepmedia You're welcome! I also transferred this to the correct repo.

This is not currently possible - see #150. Closing as a duplicate!
