### ISSUE TITLE
resolveData on root

### ISSUE THREAD

**Issue by joaojoyce** [measuredco/puck#482]
Hi. Is `resolveData()` on root object currently working? I'm having a hard time triggering it.

I can't do it on Puck load, nor using `resolveAllData()`

Here's a simple root object...It renders the title as null, even after calling `resolveAllData()`. I can't see the console.log also, so I believe it is not being triggered.

```
{
    fields: {
        title: {
            type: "text",
        }
    },
    resolveData: async ({ props }) => {    
        console.log("RESOLVING DATA")
        return {
          props: {
            title: "Test"
          },
        };
    },
    render: ({title,children}) => {
        return (
            <div className="contentroot">
                <div>
                    <h1>{title}</h1>
                </div>
                <div>
                    {children}
                </div>
                <div>
                    <h1>Footer</h1>
                </div>
            </div>
        )
    }
}
```

Am I doing something wrong?

**Comment by chrisvxd** [comment]
Hi @joaojoyce! Thanks for your report, but unfortunately I'm unable to reproduce. I tried copying your code snippet above into the demo application and the resolver ran fine.

If you can share a repo or codepen which reproduces the issue, I can investigate further.

**Comment by joaojoyce** [comment]
Hi @chrisvxd ,

I found out that resolveData doesn't work if I pass properties to <Puck />. I also get the warning that passing properties to <Puck /> is deprecated.

So this doesn't work:

````
<Puck config={config} />
````

This does not
````
<Puck 
          overrides={{headerActions:()=>(...)}}
          onChange={(data) => {onChange({ target: {  name, value: JSON.stringify(data)}})}} 
          data={initialData} config={config}  >
</Puck>
````


Is this intended? It's very convenient and intuitive to pass these properties to puck directly. Also, this makes it easy to abstract generic configs that would work the same on `<Puck />` and on `<Render />`. 

For instance, the onChange function that I have here isn't needed on my frontend where I render...

**Comment by joaojoyce** [comment]
Nevermind. It was my initialData that was not built correctly.
