### ISSUE TITLE
Making defaultProps an asynchronous function that returns an object?

### ISSUE THREAD

**Issue by Roshan54321** [measuredco/puck#496]
I don't exactly know how I should populate the fields at first render (from external api). I don't want to call an api everytime the appState changes, rather call the api in defaultProps.

Is there a better way that exists?

**Comment by chrisvxd** [comment]
You could probably do something with resolveData and check if any data exists before deciding whether or not to call your API, but perhaps not ideal.

Wonder if a `resolveDefaultProps` API could be a good idea to match `resolveData` and `resolveFields` 🤔

**Comment by Roshan54321** [comment]
> You could probably do something with resolveData and check if any data exists before deciding whether or not to call your API, but perhaps not ideal.
> 
> Wonder if a `resolveDefaultProps` API could be a good idea to match `resolveData` and `resolveFields` 🤔

yes, but I guess an async function that returns the desired object is enough for this.

**Comment by Roshan54321** [comment]
@chrisvxd I was wondering if this is in your priority list. Would be great to have in coming release.

**Comment by chrisvxd** [comment]
It's not on my radar right now, but should be easy to implement with the existing `resolveData` functionality.

**Comment by chrisvxd** [comment]
Closing in favour of #557

**Comment by Roshan54321** [comment]
Hi @chrisvxd. Sorry to mention again. 

Regarding #557, i was thinking about the situation when you would want to give initial data to the component but using async requests. What i understand about resolveData is that it triggers everytime the data changes. I mean, it would be like i want to get 10 items for array type initially and let the user delete, add or edit according to his/her needs, but definitely don't want it to fetch 10 items again and again. 

My concept is to get the initial data from sources and let the user do anything he wants after inserting and dont go with the overhead of resolveData.

I'm not very good with these things, but please correct me.

**Comment by Roshan54321** [comment]
> @Roshan54321 I believe you could configure the resolveData API to only trigger once:
> 
> ```js
> const config = {
>   components: {
>     HeadingBlock: {
>       fields: {
>         title: {
>           type: "text",
>         },
>       },
>       resolveData: async ({ props }) => {
>         if (props.loaded) return;
>        
>         return {
>           props: {
>             title: "Hello, world",
>             loaded: true
>           },
>         };
>       },
>       render: ({ title }) => {
>         return <h1>{title}</h1>;
>       },
>     },
>   },
> };
> ```

Yes, i been doing like that except, it didn't work on first load. This now looks fixed. But still i feel bad using resolveData (which definitely was made for another purpose) to mix my initialFetching logic. 

Thanks for looking into it!

**Comment by chrisvxd** [comment]
@Roshan54321 that's a fair concern. I generally prefer explicit APIs, too, but in this case worry about the amount of complex logic that underpins `resolveData`.

For the time-being, I don't think there's anything hugely wrong with using `resolveData` in this way.
