### ISSUE TITLE
Feature request: Allow mapRow to return more than just string and number types

### ISSUE THREAD

**Issue by goynang** [measuredco/puck#506]
How about letting the `mapRow` function on `external` fields return more types than just `string` and `number`?

For example, if it also allowed `React Node` (or`React Element`?) you could do things like show thumbnail images for the items listed. This would make the `external` selection feature far more powerful.

Alternatively, maybe allowing an override for the list renderer would allow even more flexibility?

**Comment by vladninja** [comment]
I have the same case. Need to show a list of the images (thumbnails) in the popup, because the filename is not what the user want to see.

**Comment by camhammel** [comment]
Created a PR to resolve this 👍 just a matter of adjusting the typing:
![image](https://github.com/user-attachments/assets/3aba6e77-06c2-488d-9df9-c8c662675bf1)
```
       mapRow: (item) => ({
        img: (
          <img
            src="https://placehold.co/600x400"
            alt="important"
            height="40"
            width="60"
          />
        ),
        title: item.title,
        description: item.description,
      }),
```
