### ISSUE TITLE
How do you want to engage with Puck?

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#51]
The last few days have been a blast - we've gone from 8 stars on Tuesday morning to 2.1k and counting on Thursday.

We've been thinking a lot about the best way to engage with you all.

Currently we're considering:

1. GitHub only (issues, discussions and releases)
2. X/Twitter (via the [@hellomeasuredco account](https://twitter.com/hellomeasuredco), or a new dedicated account)
3. Discord
4. Mailing list

Are there any things we're missing, or anything you'd like us to consider? Free-form responses welcome.

**Comment by xaviemirmon** [comment]
@chrisvxd I'd love to chat on Discord!

**Comment by sagarchoudhary96** [comment]
**GitHub only**  +1, with so many discord channels nowadays and then github issues/disccussions as well it becomes sometime hard to find required info/help. i feel like keeping it at one place makes it easier to access and manage too 🙂

**Comment by monospaced** [comment]
Notwithstaning that it does feel like Discord is the way things are going these days: 

[Don't use Discord as your Q&A forum](https://kraktoos.com/posts/dont-use-discord-as-forum/)

**Comment by chrisvxd** [comment]
We've created a Discord server:  https://discord.gg/D9e4E3MQVZ (@xaviemirmon @spellew)

We'll also continue to actively engage via GitHub.

We didn't get tonnes of feedback on this, but decided to open a Discord as we want a place to engage with the community more synchronously. We want to hear more of what people doing with Puck, and also have a way to engage with non-technical users of Puck (like content teams).

I understand and share the concerns regarding finding the necessary information, so we'll aim to to keep GitHub thriving and direct people here from Discord where appropriate. Our hope is this may also have the effect of raising the quality of issues opened on GitHub. If it becomes difficult to maintain or isn't working for our users, we'll move back to GitHub only.

Aside - I'm also open to exploring the use of Discord bots to index things on GitHub.
