### ISSUE TITLE
Is there any way to load the live data or server side rendering of data live data 

### ISSUE THREAD

**Issue by umashankar-pardhi-amla** [measuredco/puck#510]
I am impress with puck, but looking for solution where I can load the live data 

I have some component those are handing the live data on client side as well as server side.

**Comment by chrisvxd** [comment]
You can load live data using [dynamic props](https://puckeditor.com/docs/integrating-puck/dynamic-props), or by requesting data inside your component as you normally would. Puck components are just React components.
