### ISSUE TITLE
resolveData is not called when a component is placed in the editor

### ISSUE THREAD

**Issue by etimberg** [measuredco/puck#511]
## Background

* Puck version: `0.15.0`

## Current Behaviour

I have a component that loads data via `resolveData`. When this component is placed into the editor, no data is loaded. I have breakpointed `resolveData` and I can see that it is not called. My understanding of the editor was that this should happen automatically.

## Expected Behaviour

When a component that has `resolveData` defined is placed into a page, `resolveData` should be called on the new component.

**Comment by chrisvxd** [comment]
Thanks for the report and sorry for the delay. I'll investigate this and see if I can reproduce.

**Comment by azharuddin-mulla-amla** [comment]
@chrisvxd we also facing same issue.
