### ISSUE TITLE
Adding Card Previews on Hover

### ISSUE THREAD

**Issue by Sarfraz-droid** [measuredco/puck#522]
Hi, are there any plans for adding Popover previews for Drawer Items on hover? If not, is there any way we can do it manually??

<img width="286" alt="Screenshot 2024-06-27 at 9 41 46 AM" src="https://github.com/measuredco/puck/assets/73013838/65ee67b2-6d1c-4a1d-912f-e7d69401f2cb">

**Comment by IMythx** [comment]
i suppose u can override the component item via plugin or the override prop

**Comment by chrisvxd** [comment]
What @IMythx  said - it's possible to [override](https://puckeditor.com/docs/extending-puck/custom-interfaces#ui-overrides) the [component item](https://puckeditor.com/docs/api-reference/overrides/component-item) to achieve something like this.
