### ISSUE TITLE
Use only Turborepo and pnpm

### ISSUE THREAD

**Issue by BleedingDev** [measuredco/puck#55]
It seems that this is the way that tooling is going. 

- [x] I am willing to work on this

**Comment by chrisvxd** [comment]
Hey @BleedingDev! Thanks for bringing this up, but it's not a high priority for us right now.

In particular:

* Yarn is how we work at @measuredco, so this makes it easier for us to context switch
* Whilst the monorepo is mostly managed by turbo, I believe we still need lerna for our release automation

The package manager space is constantly changing so slightly hesitant to jump on the pnpm train just yet (for example, bun has been making a lot of noise in the last week).

We might revisit this in the future - feel free to make a PR if you feel strongly, but I don't think we'll be ready to accept it at this time.

**Comment by Jonohas** [comment]
I would agree, this would be nice. Especially since we started using bun for all our bundling etc. Also created a plugin for bun that can generate configs from a fiilesystem, similar to file based routers like tanstack router or any other one.
