### ISSUE TITLE
How to use it with  Vite?

### ISSUE THREAD

**Issue by localhosted** [measuredco/puck#56]
I tried using the demo in Vite but I am stuck on "Failed to resolve import "@measured/puck/components/Puck""

This file doesn't exist on the NPM package's dist folder, what am I missing?

**Comment by chrisvxd** [comment]
Hey @localhosted, thanks for the report. I don't have any experience with Vita and will leave this ticket here until I get a chance to test it properly.

It could be as simple as going to the root of the repo and running `yarn` to get all packages in the workspace compiled properly, but it could also be something Vite specific.

**Comment by localhosted** [comment]
The problem is that the demo is in a monorepo that uses nextjs transpiler options to access private components/packages

Running the code from the create-puck-app should work as it's a more basic example with no private package/path imports
