### ISSUE TITLE
The page is not rendering server side.

### ISSUE THREAD

**Issue by deevo-sage** [measuredco/puck#560]
The page does not render server side and everything is just a script that is running on client side.
- very high TBT and other core metrics

using `import { Render } from "@measured/puck/rsc"`

<img width="646" alt="image" src="https://github.com/user-attachments/assets/b2c8f79d-a9a7-4c7a-a10c-de2a9c1f0e1e">

**Comment by deevo-sage** [comment]
was my fault

**Comment by mani-rai** [comment]
It's still not working for me with `0.18.3` in next.js. Tried with simplest example possible: [https://stackblitz.com/edit/stackblitz-starters-dfjvpdfr](Example)

**Comment by FedericoBonel** [comment]
Hey @mani-rai,

I don't fully understand your example. All you're doing in your Page component is providing the `<Render />` component with an empty initial data and a simple config.

If you wanted to render a page there, you need to provide it in the [`data` prop](https://puckeditor.com/docs/api-reference/components/render#data) of the `<Render />` component.

**Comment by mani-rai** [comment]
Hey @FedericoBonel, just confirmed and it's working. I needed to configure data as well. Thanks.
