### ISSUE TITLE
Custom field type  and custom field input 

### ISSUE THREAD

**Issue by localhosted** [measuredco/puck#57]
How can I create a new field type and it's editor?

The current plugin system doesn't seem to support this, only allowing us to reimplement the whole sidebar editing?

**Comment by chrisvxd** [comment]
@localhosted We don't support this yet but it's high priority. I'm hoping to get to it soon!

**Comment by chrisvxd** [comment]
@localhosted I've put together a proposal for this. Let me know if you have any feedback on #58!
