### ISSUE TITLE
Frame issue

### ISSUE THREAD

**Issue by Sahak885** [measuredco/puck#571]
Puck Editor (version: 0.15.0)
Stack: Next JS pages router (version: 13.1.2)

**Provide environment information**

```
Binaries:
  Node: 20.11.0
  npm: 10.2.4
  Yarn: 1.22.21
  pnpm: N/A
Relevant Packages:
  next: 13.1.2
  eslint-config-next: 13.1.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 4.9.4
```
Loom Video: https://www.loom.com/share/4f7a8a79b8244e8b980668a2e108f595

It worked correctly in development mode, but when I ran `npm run build` and `npm run start`, it didn't work correctly in production mode.

**Comment by Sahak885** [comment]
I think the issue occurred in this code.
![image](https://github.com/user-attachments/assets/a3c9d609-6926-4bec-9e4e-211077d766eb)

**Comment by chrisvxd** [comment]
Hey @Sahak885 - it sounds like some of your styles. may not be loading. Can you check in your network tab if everything is completing?

Puck defers showing the iframe until the initial styles have loaded. We can consider adding an API to disable this behaviour.

**Comment by chrisvxd** [comment]
Hey @Sahak885 - please try the new `iframe.waitForStyles = false`  config in the latest canary as a workaround.

**Comment by chrisvxd** [comment]
Canary is done on every merge, and listed here: https://www.npmjs.com/package/@measured/puck?activeTab=versions

However, `v0.16.0` is out now and includes the above API.
