### ISSUE TITLE
Type errors with TypeScript strict mode

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#575]
Users have reported errors when using TS strict mode:

## Steps to reproduce

Create a project with TypeScript strict mode enabled, and the following type definition:

```ts
type RootProps = {
    font: string;
    children: ReactNode;
} & DefaultRootProps;

type PuckConfig = Config<Components, RootProps>;
```

## What happened

The following building error occurs:

```
Type 'PuckConfig' does not satisfy the constraint 'Config'.
  Types of property 'root' are incompatible.
```

## What I expected to happen

No build error to occur

**Comment by IMythx** [comment]
doesnt PR#548 fix that error?

**Comment by chrisvxd** [comment]
Sorry @IMythx - I've been meaning to review #548. It might fix the error but it changes the types in a way that we don't necessarily want by just making them looser. Will need a bit further investigation.

**Comment by IMythx** [comment]
> Sorry @IMythx - I've been meaning to review #548. It might fix the error but it changes the types in a way that we don't necessarily want by just making them looser. Will need a bit further investigation.

Ok got it

**Comment by chrisvxd** [comment]
@IMythx could you confirm if [0.16.0-canary.6d43ba0](https://www.npmjs.com/package/@measured/puck/v/0.16.0-canary.6d43ba0) (from #592) addresses your vite issues?

**Comment by IMythx** [comment]
> @IMythx could you confirm if [0.16.0-canary.6d43ba0](https://www.npmjs.com/package/@measured/puck/v/0.16.0-canary.6d43ba0) (from #592) addresses your vite issues?
yeah it did fix the issue with strict mode on
thx

**Comment by IMythx** [comment]
> @IMythx could you confirm if [0.16.0-canary.6d43ba0](https://www.npmjs.com/package/@measured/puck/v/0.16.0-canary.6d43ba0) (from #592) addresses your vite issues?

yeah it did fix the issue with strict mode on
Thx
