### ISSUE TITLE
[QUESTION] React Styled Components

### ISSUE THREAD

**Issue by MiniMarPaz** [measuredco/puck#576]
Hello.

I've started to use Puck recently and stumbled upon weird thing so maybe can help me answer that question.
In our project we are using styled-components to style our React components. However when I'm creating new component for Puck styles are not displayed in the editor itself. However inline styling works fine. Maybe someone stumbled on similar thing? Or maybe Puck does not support styled-components and support only inline styling? 

Thank You.

**Comment by chrisvxd** [comment]
Hi and welcome @MiniMarPaz - this sounds like a bug and might be related to #543.

To check, try [disabling iframes](https://puckeditor.com/docs/integrating-puck/viewports#opting-out-of-iframes). If this fixes the issue, please add your example to #543, ideally with some code to reproduce.

**Comment by MiniMarPaz** [comment]
Hey @chrisvxd . Yes, You were right. Disabling iframes indeed fixes the issue. Thank You!

**Comment by chrisvxd** [comment]
Closing this and will track in #543
