### ISSUE TITLE
Not work with mantine UI

### ISSUE THREAD

**Issue by woody146** [measuredco/puck#591]
In editor, it can't display ui correctly

![image](https://github.com/user-attachments/assets/967f4bd2-e992-42d9-b7f0-456c0012d0d9)

But in Render, it displays oke

![image](https://github.com/user-attachments/assets/087d7f08-cac0-44aa-b077-9f637f3ba8df)

I built sample project at https://github.com/woody146/test-remix. Run `npm run dev` then go to `http://localhost:5173/puck` to check it

**Comment by chrisvxd** [comment]
This should be fixed in canary - see #543. I'm going to close this, but let me know if the canary isn't working for you.

**Comment by woody146** [comment]
> This should be fixed in canary - see #543. I'm going to close this, but let me know if the canary isn't working for you.

Thanks, it's fixed in canary
