### ISSUE TITLE
Feature Request: Sub objects

### ISSUE THREAD

**Issue by Danm72** [measuredco/puck#60]
It would be nice to be able to add sub objects pretty much exactly the way `arrayFields` currently behaves just without the 'add item' UI!

For example in the demo site we have full blocks like `Hero` which only have some theme/config options but we also have components like `H1` on the page at the same time.

The `Hero` likely contains a H1 and it would be nice to be able to edit the H1 as a dedicated object.

![Export-1694337157447](https://github.com/measuredco/puck/assets/1926968/1afa4326-10bd-4533-ab48-c65277ce9b1a)

**Comment by chrisvxd** [comment]
Great suggestion, discussion via PR #62

**Comment by chrisvxd** [comment]
Closing this in favour of #64 for now. May revisit in future.

**Comment by Danm72** [comment]
Awesome fair play you keeping this moving!
