### ISSUE TITLE
A component, most of the time it doesn't render completely in Firefox and sometimes in Chrome, and fewer times in Edge.

### ISSUE THREAD

**Issue by cigotete** [measuredco/puck#641]
Hello everyone.
I have a problem using Puck (0.15.0) with Firefox and I found that issue is happening also in Chrome. When I add a component, most of the time (Firefox) it doesn't render completely, but only when a next component is added, then the previous component is displayed correctly. Very few times, components render ok on first attempt of addition. I have several types of components, some with Ant Design System, others with Styled Components, and the same thing happens to them.

I found first the issue in Firefox because is the browser that I was using to test. When I tested the issue in Chrome, at firsts try, the issue was not happening with components that I was working on, but eventually I found that the issue happens with some components (much less than Firefox). I have tested all components involved in my tests on Edge and the issue is not happening on Edge.

I have updated to Puck 0.16.0 and issues are happening too, as was described before.

Thanks @chrisvxd for your suggestion about let this issue on GitHub.

In the message on Discord, a member said (Azhar) that also is happened to him in Chrome https://discord.com/channels/1153376562259951687/1153376562830397563/threads/1289659599640596500

**Comment by cigotete** [comment]
I managed to reproduce the issue in Edge. It is happening few times, and with fewer components. If are added same components with same order gives issues sometimes and others no. If you start to interact with the browser, there are issues with some components, but if you reload the browser, the components that were presenting issues are added n displayed ok from the first interaction, sometimes this behavior described is not happening.

Maybe is something with my components, but I want to say that I am using Cosmos as component viewer to build each component, and there are no issues when those components are displayed on that context. Maybe is something related with styles rendering inside Puck environment that I need to discover/understand.

**Comment by chrisvxd** [comment]
@cigotete would you be able to provide a repo that reproduces this issue?

**Comment by cigotete** [comment]
Thanks for your answer. I found a couple of the issues related.

I am using a modal to show Puck editor, I removed the modal, and the times that the issues happens have reduced ostensibly (using Chrome, I have several days without the issue by except few times that happens). Also I started to use a Google font, that uses as default the feature "preconnect" and the issue arrives again and never disappear. So these are external conditions that are affecting the process of render.
I think that is not an Issue with Puck, seems is related with conditions around process of render the component, in the interaction with Puck (this is no happening when I check components with Cosmos as isolated components).

BTW, I did not close the issue. I am not sure what kind of key combination I pressed, and the issue has been marked as completed. But I think that the issue can be closed, because this case can be solved with improvements of components.

**Comment by cigotete** [comment]
As an update, specifically the issue of incomplete render of Components that uses Styled Components or Ant DS is because currently Puck uses iframe for the workspace, so components are render inside that iframe (is an architectural consideration, not an issue), and that must be considered using Styled Components or AntDS because an iframe creates its own separated document context. Then injecting those styles on the iframe solves the issue (using ConfigProvider for AntDS and StyleSheetManager for Styled Components).

**Comment by chrisvxd** [comment]
Thanks @cigotete. This sounds similar to issues encountered with emotion (which we created a [plugin](https://github.com/measuredco/puck/tree/main/packages/plugin-emotion-cache). Sounds like we might need something for Ant / Styled Components, too.
