### ISSUE TITLE
Patch / fork react-beautiful-dnd to fix React defaultProps warning

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#65]
[react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd) is somewhat dated and hasn't kept pace with React releases:

<img width="1282" alt="image" src="https://github.com/measuredco/puck/assets/985961/998c464f-c934-4ff8-91f9-12534b89c3d9">

## Options

* Patch upstream
* Fork and patch our own version under `@measured` npm scope
* Patch package inline

**Comment by chrisvxd** [comment]
Awesome, thanks @ahmedrowaihi. I've forked to https://github.com/measuredco/react-beautiful-dnd.

**Comment by chrisvxd** [comment]
@ahmedrowaihi are you looking at this one? If not, I plan on picking it up next week.

**Comment by chrisvxd** [comment]
Good luck with your exams! Totally takes priority and thanks for letting me know @ahmedrowaihi

**Comment by 4leite** [comment]
fyi this looks to be a currently maintained successor (same api but up to date libraries) that may save you some work:
https://github.com/hello-pangea/dnd see for eg https://github.com/hello-pangea/dnd/releases
disclaimer: have not tested if it works

**Comment by chrisvxd** [comment]
@4leite you're a life-saver, I've been looking for an active fork. Tested it and works as a drop-in replacement. Going to make the PR now.
