### ISSUE TITLE
Type: radio not clickable in arrayFields

### ISSUE THREAD

**Issue by thopedam** [measuredco/puck#653]
Radio Fields inside arrayFields are not clickable in puck 0.16.1

Might be related: https://github.com/measuredco/puck/pull/643

**Comment by joeyhotz** [comment]
can confirm facing the same issue. will revert to just using a select for now

**Comment by chrisvxd** [comment]
Ah this is a dupe of #723, which has been closed. Apologies for slow reaction to this one.
