### ISSUE TITLE
history.historyStore is undefined when using Puck in Remix

### ISSUE THREAD

**Issue by lodybo** [measuredco/puck#658]
I'm trying to write a plugin to use TinyMCE's rich text editor with Puck, heavily based on the [`puck-rich-text`](https://github.com/Tohuhono/Oberon/tree/main/packages/tohuhono/puck-rich-text) package (which uses Lexicon). I'm stuck at the implementation of the `useSelected` hook, which in `puck-rich-text` is being used to make sure the Rich Text Editor is actually selected before dispatching the `onChange` event.

I can add my editor and add content to it, but when I save my page (or rather, when the page is normally loaded), an error is thrown:

```
TypeError: Cannot read properties of undefined (reading 'hasPast')
```

It seems that `history` is undefined when returned from `useAppContext()`.

[I've created a reproduction here](https://github.com/lodybo/puck-history-reproduction) that you can run. The instructions are in the README.

**Comment by IMythx** [comment]
as i remember this error happens when u call `usePuck` hook outside of `<Puck/>` since this component returns the context provider so you can't consume the context outside of it

**Comment by lodybo** [comment]
Apologies since I've had a few things come up. I dove into this after @IMythx's comment and he is indeed correct and wanted to add some more context here.

The reason this came up is because the `Render` component is missing the Puck context entirely but _is_ getting al the components from the configuration passed to it.

So if you're component uses `usePuck()` in its `render()` function (like you maybe would with WYSIWYG editors), this error comes up when Puck is in render-mode.

The solution is to return components:

```jsx
export const MyPlugin = {
  fields: {},
  render: ({ content, id, puck }) => {
    if (puck.isEditing) {
      // usePuck is called inside RichTextEditor
      return <RichTextEditor id={ id } initialValue={ content } />;
    }

    return <div dangerouslySetInnerHTML={{ __html: content }} />;
  }
}
```
