### ISSUE TITLE
AutoField missing icons for some field types

### ISSUE THREAD

**Issue by IMythx** [measuredco/puck#662]
the ones i noticed are `object` and `radio` field types

**Comment by IMythx** [comment]
actually its a `FieldLabel` issue not `AutoField`

**Comment by IMythx** [comment]
well maybe its not a bug its just waiting from the user to wrap it in a `FieldLabel` and provide his own icon and styling (cuz `FieldLabel` is missing some inline padding comparing to `FieldLabelInternal` which is one the `FieldLabelPrivate` is using)

**Comment by chrisvxd** [comment]
As you've identified, this is a feature request related to FieldLabel rather than a bug. FieldLabel accepts an `icon` prop, documented here: https://puckeditor.com/docs/api-reference/components/field-label#icon

I'll create a new ticket with a relevant proposal and link it here.

**Comment by chrisvxd** [comment]
Here's the feature issue: #686
