### ISSUE TITLE
<AutoField> vs. <AutoFieldPrivate> styling differences

### ISSUE THREAD

**Issue by benlife5** [measuredco/puck#666]
I've been working on a fields override to allow editing some global styles and used `<AutoFieldPrivate>` because it is styled perfectly when rendered directly in the override and`<AutoField>` is not.

Per #661, `<AutoFieldPrivate>` shouldn't be exported (which makes sense). However, I wanted to flag that `<AutoField>` isn't a direct replacement. 

```
const field = {
  "label": "Colors",
  "type": "object",
  "objectFields": {
    "foreground": {
    "label": "Foreground",
    "type": "select",
    "options": [
      {"value": "#000000", "label": "Black" },
      {"value": "hsl(0 68% 51%)", "label": "Red"}]
    },
    "primary": {
      "label": "Primary",
      "type": "object",
      "objectFields": {
        "DEFAULT": {
          "type": "custom",
          "label": "Default"
        },
        "foreground": {
          "type": "custom",
          "label": "Foreground"
        }
      }
    }
  }
}

const value = {
  "foreground": "#000000",
  "primary": {
    "DEFAULT": "#a73fd1",
    "foreground": "#ffffff"
  }
}
```

```
return (
  <AutoFieldPrivate
    field={field}
    onChange={(value) => onThemeChange(parentStyleKey, value)}
    value={values}
  />
);
```
![Screenshot 2024-10-22 at 1 44 20 PM](https://github.com/user-attachments/assets/659c7e0a-2630-4ba4-aca1-68762f3edb73)

```
        return (
          <FieldLabel key={parentStyleKey} label={field.label!}>
            <AutoField
              field={field}
              onChange={(value) => onThemeChange(parentStyleKey, value)}
              value={values}
            />
          </FieldLabel>
        );
```
![Screenshot 2024-10-22 at 1 46 56 PM](https://github.com/user-attachments/assets/27f0bec4-5eee-4854-b4ef-11671eced9bc)

**Comment by IMythx** [comment]
i alrdy mentioned that in [#662](https://github.com/measuredco/puck/issues/662) that its missing icons for first lvl fields.

but then i realized its not a bug rather than its waiting from you to wrap it into a `FieldLabel` and provide your own icon and styling (cuz `FieldLabel` is missing some inline padding compared to `FieldLabelInternal` which is the one used by `AutoFieldPrivate`)

**Comment by IMythx** [comment]
![image](https://github.com/user-attachments/assets/acbcb37c-3e4c-46ec-af39-91ec9466ea62)

as you u can see here that `Label` prop which is causing the issue (if we call it so) meanwhile `AutoFieldPrivate` doesnt provide that prop so it uses the default value for the `Label` prop which is `FieldLabelInternal` as u can see in the following ss

![image1](https://github.com/user-attachments/assets/44ad5637-bdca-4489-a673-cc6eddefde40)

**Comment by IMythx** [comment]
it will be perfect for us if it doesnt provide that `Label` prop but then there would no point of the `FieldLabel` component

**Comment by IMythx** [comment]
@chrisvxd  maybe yeah just remove the `FieldLabel` component entirly and provide the `FieldLabelInternal` component to the `AutoField` component instead of that `DefaultLabel` and let us pass the icon and label via `AutoField` if we want otherwise use the default ones

**Comment by chrisvxd** [comment]
Hey both. Removing AutoField here: https://github.com/measuredco/puck/pull/685

To answer questions about the differences

1. field.label is ignored by AutoField. I've removed it from the type the PR.
2. FieldLabel is the correct way to do this
3. I can't reproduce your issues @benlife5, and have [added an example](https://github.com/measuredco/puck/pull/685/files#diff-b73170638dc9c5e97d445c543e218726d5524b1d5b5c70cf78d2c84325f41f42R121-R137) to the Hero component in the demo, which uses the AutoField inside an object field as you are. It renders as expected, so you might have something else going on.

**Comment by benlife5** [comment]
Thanks for taking a look at this @chrisvxd!

My issue was coming up when doing a fields override and then rendering these components directly in the override. It seems like the issue with margin/padding was fixed. However, FieldLabel still renders without the expected styling.

Here's a demo: https://stackblitz.com/edit/vitejs-vite-gw1ksa?file=src%2FEditor.tsx.

I get this may not really be a supported use case so I understand if I should just add my own styling and close out this issue.
