### ISSUE TITLE
Strip leading zeros in Number Field

### ISSUE THREAD

**Issue by benlife5** [measuredco/puck#694]
When you delete the value in NumberField, it resets to 0. However, once you type in another number, it keeps the leading 0. Ideally, this would be stripped as the user is typing.

https://github.com/user-attachments/assets/08c77494-0278-4c1f-b2be-a65c7f5dbefa

https://stackblitz.com/edit/vitejs-vite-ncvhwx?file=src%2FEditor.tsx

**Comment by chrisvxd** [comment]
Closed by #695
