### ISSUE TITLE
Rich Text Support

### ISSUE THREAD

**Issue by bakikucukcakiroglu** [measuredco/puck#710]
Hello,

I need rich text features like bold, italic, underline etc. I tried to use [puck-rich-text](https://www.npmjs.com/package/@tohuhono/puck-rich-text) but it is not working with the current version of Puck. Is it possible to add this as a built in component since it is a very fundamental need for every developer?

If there is a way that I'm missing, please let me know.

**Comment by thopedam** [comment]
you can download the puck-rich-text lib, copy the `useSelected` hook and use something like [tiptap](https://tiptap.dev)

```javascript
const RichTextEditor = ({ content, id, columns }: RichTextEditorProps) => {
  const { isSelected, onChange } = useSelected(id);
  const editor = useEditor({
    content,
    // [...] more tiptap settings
    onUpdate: ({ editor }) => {
      onChange({ content: editor.getHTML() });
    },
  });

  return (
    <div
      style={{
        cursor: isSelected ? "auto" : "grab",
        pointerEvents: "auto",
      }}
    >
      <EditorContent editor={editor} />
      {editor && <RichTextToolbar editor={editor} id={id} />}
    </div>
  );
};
```

Add a Toolbar (toolbar override check puck docu)
```javascript
type Props = {
  editor: Editor;
  id: string;
};

const RichTextToolbar = ({ editor, id }: Props) => {
  return (
    <ActionToolbar id={id}>
      <ActionBarButton
        isActive={editor.isActive("bold")}
        onClick={() => editor.chain().focus().toggleBold().run()}
      >
        <Bold size={16} />
      </ActionBarButton>
      <ActionBarButton
        isActive={editor.isActive("italic")}
        onClick={() => editor.chain().focus().toggleItalic().run()}
      >
        <Italic size={16} />
      </ActionBarButton>
      <ActionBarButton
        isActive={editor.isActive("underline")}
        onClick={() => editor.chain().focus().toggleUnderline().run()}
      >
        <Underline size={16} />
      </ActionBarButton>
    </ActionToolbar>
  );
};
```

**Comment by bakikucukcakiroglu** [comment]
Thanks for your insight! I made it work.

**Comment by chrisvxd** [comment]
Closing in favour of #149

**Comment by juzo** [comment]
Hey @bakikucukcakiroglu did you make this **tiptap** solution work with the latest puck v`0.18.2` ?

I am having issues with the 'focus' (event propagation) - as if puck dnd engine is only allowing me to drag the component not to edit the content.

**Comment by AyoubBelhaj** [comment]
@bakikucukcakiroglu I'm trying to do the same, I want to use @tohuhono/puck-rich-text and add to it more options can you provide more details for me please.
