### ISSUE TITLE
Radio fields not working inside arrays

### ISSUE THREAD

**Issue by chrisvxd** [measuredco/puck#723]
## Description

Radio fields are not working in arrays. Root cause: https://github.com/measuredco/puck/pull/643

## Steps to reproduce

1. Click ButtonGroup near the bottom of the demo page
2. Click first item in `buttons` array
3. Change new radio option

## What happens

Input did not react

## What I expected to happen

Input reacts and value is changed

## Considerations

Ensure that a regression is not introduced.

**Comment by jswhisperer** [comment]
Is this the right component? on this url https://demo.puckeditor.com/ 
https://github.com/user-attachments/assets/36e736a4-97ab-42cf-a8cf-a06ce7bae21f

**Comment by chrisvxd** [comment]
Sorry @jswhisperer - the bug is in the editor field, not on the demo page itself.

**Comment by jswhisperer** [comment]
Should be addressed here https://github.com/measuredco/puck/pull/732
