### ISSUE TITLE
Error in utils file

### ISSUE THREAD

**Issue by uidevencriss** [measuredco/puck#753]
ERROR in src/core/types/Utils.tsx:46:45
TS2344: Type 'UserData["content"][0]' does not satisfy the constraint 'ComponentData<DefaultComponentProps, string>'.
  Type 'ComponentData<any, string> | ComponentDataMap<UserProps>' is not assignable to type 'ComponentData<DefaultComponentProps, string>'.       
    Type 'ComponentDataMap<UserProps>' is not assignable to type 'ComponentData<DefaultComponentProps, string>'.
      Type 'ComponentData<UserProps[keyof UserProps], keyof UserProps extends string ? string & keyof UserProps : never>' is not assignable to type '{ type: string; props: WithId<DefaultComponentProps>; }'.
        Type 'UserData["content"][0]' is not assignable to type '{ type: string; props: WithId<DefaultComponentProps>; }'.
          Type 'ComponentData<any, string> | ComponentDataMap<UserProps>' is not assignable to type '{ type: string; props: WithId<DefaultComponentProps>; }'.
            Type 'ComponentDataMap<UserProps>' is not assignable to type '{ type: string; props: WithId<DefaultComponentProps>; }'.
              Types of property 'props' are incompatible.
                Property 'id' is missing in type 'WithId<UserProps[keyof UserProps]>' but required in type 'WithId<DefaultComponentProps>'.       
    44 |   >,
    45 |   UserAppState extends AppState<UserData> = AppState<UserData>, 
  > 46 |   UserComponentData extends ComponentData = UserData["content"][0]
       |                                             ^^^^^^^^^^^^^^^^^^^^^^
    47 | > = {
    48 |   UserConfig: UserConfig;
    49 |   UserProps: UserProps;

how to solve this issue please explain

How can I integrate all component of  Puck Editor into my code?
Please help i install your library npm i @measured/puck --save it does not give any component like header paragraph etc please help and solve above issue

**Comment by chrisvxd** [comment]
Hi @uidevencriss - not possible to debug from your message. Please use [GitHub markdown formatting](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) to to break up the message in future.

For now, I recommend following this guide: https://measured.co/blog/building-a-react-page-builder-an-introduction-to-puck
