### ISSUE TITLE
Adding support to sort Component List

### ISSUE THREAD

**Issue by sagarchoudhary96** [measuredco/puck#78]
Current the puck Editor renders the Components List by map `Object.keys(config.components)`. it will be great if we can have ability to control the order of rendering this List.

**Comment by chrisvxd** [comment]
Hi @sagarchoudhary96! `Object.keys()` respects the order of keys in the object, so you can sort your components by reordering the keys in `components`.

**Comment by chrisvxd** [comment]
Have closed the issue, but let me know if that's not working or if there's something else you're trying to achieve.

**Comment by sagarchoudhary96** [comment]
Thanks, Works
