### ISSUE TITLE
Elements lose hover after some time

### ISSUE THREAD

**Issue by localhosted** [measuredco/puck#81]
After adding some elements the previous ones lose the hover border and actions:

https://github.com/measuredco/puck/assets/8821661/999eb753-7545-4411-9425-12e95d68c1f8

**Comment by chrisvxd** [comment]
Thanks for this report @localhosted. Suspect it might be resolved by https://github.com/measuredco/puck/pull/37, which reimplements a lot of the hover functionality. Let's re-test once #37 is merged.

**Comment by chrisvxd** [comment]
Hi @localhosted  - can you confirm if this is still occurring in the `0.8.0` canary?

**Comment by chrisvxd** [comment]
Closing as can't reproduce
