### ISSUE TITLE
Components with hooks don't really work

### ISSUE THREAD

**Issue by Manuelbaun** [measuredco/puck#82]
Hi, 

first of all, thank you for the library, It is really promising. At the moment I have some issues with hooks, where I try to use useEffect to subscribe to an api endpoint (for now, just pull data, in an interval), then I want to display the current value.

When I try to add my component via dnd, then react complains about `more hooks are rendered then in the previous render` error. It basically points to useState, or useEffect, what ever comes first.

I wonder, how can I manage to do it? 

This fails: 
```tsx
 // ... components
 MyComponent: {
            render: () => {
                const { counter, setCounter } = useState(0);

                return (
                    <>
                        <div>Clicked {counter} times</div>
                        <button onClick={() => setCounter(counter + 1)}>Click me</button>
                    </>
                );
            },
        },
```

**Comment by chrisvxd** [comment]
Hi @Manuelbaun, thanks for the report!

I remember encountering this previously. Definitely a bug, but I think you can work around it by moving your component definition outside of your render. Let me know if that helps.

```tsx
 const MyComponent = () => {
  const { counter, setCounter } = useState(0);

  return (
    <>
      <div>Clicked {counter} times</div>
      <button onClick={() => setCounter(counter + 1)}>Click me</button>
    </>
  );
};

const config = {
  MyComponent: {
    render: () => {
      return <MyComponent />;
    },
  },
};
   ```

**Comment by Manuelbaun** [comment]
Hi @chrisvxd , 

thank you for the very fast response. Yes this worked. Very easy work around.

**Comment by abhirocks550** [comment]
> Hi @Manuelbaun, thanks for the report!
> 
> I remember encountering this previously. Definitely a bug, but I think you can work around it by moving your component definition outside of your render. Let me know if that helps.
> 
> ```tsx
>  const MyComponent = () => {
>   const { counter, setCounter } = useState(0);
> 
>   return (
>     <>
>       <div>Clicked {counter} times</div>
>       <button onClick={() => setCounter(counter + 1)}>Click me</button>
>     </>
>   );
> };
> 
> const config = {
>   MyComponent: {
>     render: () => {
>       return <MyComponent />;
>     },
>   },
> };
> ```

I am using below code 

```
import { Puck } from "@measured/puck";
import "@measured/puck/puck.css";
import { useState } from "react";


const MyComponent = () => {
    const { counter, setCounter } = useState(0);

    return (
        <>
            <div>Clicked {counter} times</div>
            <button onClick={() => setCounter(counter + 1)}>Click me</button>
        </>
    );
};

const config = {
    components: {
        MyComponent: {
            fields: {},
            render: () => {
                return <MyComponent />;
            },
        }
    },
};

// Describe the initial data
const dataObjectToCopy = {};

const initialData = dataObjectToCopy

// Save the data to your database
const save = (data) => {
    console.log(data);
};

// Render Puck editor
export function Editor() {
    return <>
        <div>
            <Puck
                config={config}
                data={initialData}
                onPublish={save}
                overrides={{
                    headerActions: ({ children }) => (
                        <>
                            <button onClick={() => alert("Navigating back to reports.")}>Navigate Back to Reports</button>
                            {children}
                        </>
                    )
                }}

            />
        </div>
    </>
}
```

When I move over cursor over the button it activates drag behaviour. 


![image](https://github.com/user-attachments/assets/11a0380d-bf60-4e6c-9927-2d2d7fbfc461)

I am not able to click onto button, am I missing something?

**Comment by abhirocks550** [comment]
> > Hi @Manuelbaun, thanks for the report!
> > I remember encountering this previously. Definitely a bug, but I think you can work around it by moving your component definition outside of your render. Let me know if that helps.
> > ```tsx
> >  const MyComponent = () => {
> >   const { counter, setCounter } = useState(0);
> > 
> >   return (
> >     <>
> >       <div>Clicked {counter} times</div>
> >       <button onClick={() => setCounter(counter + 1)}>Click me</button>
> >     </>
> >   );
> > };
> > 
> > const config = {
> >   MyComponent: {
> >     render: () => {
> >       return <MyComponent />;
> >     },
> >   },
> > };
> > ```
> 
> I am using below code
> 
> ```
> import { Puck } from "@measured/puck";
> import "@measured/puck/puck.css";
> import { useState } from "react";
> 
> 
> const MyComponent = () => {
>     const [counter, setCounter] = useState(0);
> 
>     return (
>         <>
>             <div>Clicked {counter} times</div>
>             <button onClick={() => setCounter(counter + 1)}>Click me</button>
>         </>
>     );
> };
> 
> const config = {
>     components: {
>         MyComponent: {
>             fields: {},
>             render: () => {
>                 return <MyComponent />;
>             },
>         }
>     },
> };
> 
> // Describe the initial data
> const dataObjectToCopy = {};
> 
> const initialData = dataObjectToCopy
> 
> // Save the data to your database
> const save = (data) => {
>     console.log(data);
> };
> 
> // Render Puck editor
> export function Editor() {
>     return <>
>         <div>
>             <Puck
>                 config={config}
>                 data={initialData}
>                 onPublish={save}
>                 overrides={{
>                     headerActions: ({ children }) => (
>                         <>
>                             <button onClick={() => alert("Navigating back to reports.")}>Navigate Back to Reports</button>
>                             {children}
>                         </>
>                     )
>                 }}
> 
>             />
>         </div>
>     </>
> }
> ```
> 
> When I move over cursor over the button it activates drag behaviour.
> 
> ![image](https://private-user-images.githubusercontent.com/11571357/377033369-df2e9512-d8ff-4e8b-834c-c689af28c012.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzg4NDksIm5iZiI6MTcyOTA3ODU0OSwicGF0aCI6Ii8xMTU3MTM1Ny8zNzcwMzMzNjktZGYyZTk1MTItZDhmZi00ZThiLTgzNGMtYzY4OWFmMjhjMDEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExMzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMGJiODU0MTQ4YTk0NTZmZmUxOTlkMzU0Mjc3ZmNkOGMzOTA3Mjk5ZTRhMjc1Zjc2ZTE4YWVlNzlmNDA5NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.G4hsxiNnQ4KsnO5915LorswP_cJtDXMRRg1uf4K0My8)
> 
> I am not able to click onto button, am I missing something?

Turns out to be issue with pointer-events: none. Not sure where this is getting setup and is there way to customize this. After changing pointer-events in component this is working as expected.

![image](https://github.com/user-attachments/assets/83258ca3-cda3-46c5-b74d-0759f5b978e8)
